# Generated by Django 4.2.4 on 2023-09-29 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JAB_Main', '0007_job_url_job_acceptance_chance_feeling_job_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='title',
            new_name='position',
        ),
    ]
