# Generated by Django 4.2.4 on 2023-09-29 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JAB_Main', '0008_rename_title_job_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='URL',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
