# Generated by Django 4.2.4 on 2023-09-30 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JAB_Main', '0010_alter_coverletter_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverletter',
            name='text',
            field=models.TextField(default='', null=True),
        ),
    ]
