# Generated by Django 4.2.4 on 2023-09-30 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JAB_Main', '0012_coverletter_questionnaire_how_solve_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverletter',
            name='main_self_address',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coverletter',
            name='main_self_name',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coverletter',
            name='main_subject',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
