# Generated by Django 4.2.4 on 2023-10-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JAB_Main', '0015_userconsent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='address',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
