# Generated by Django 4.2.4 on 2023-10-02 15:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('JAB_Main', '0016_alter_job_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverletter',
            name='main_cover_letter_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='coverletter',
            name='main_self_address',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='coverletter',
            name='main_self_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coverletter',
            name='main_subject',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coverletter',
            name='questionnaire_how_solve',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='coverletter',
            name='questionnaire_looking_for',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='coverletter',
            name='questionnaire_personality_strengths',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='coverletter',
            name='questionnaire_portfolio_links',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='coverletter',
            name='questionnaire_relevant_experience',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='coverletter',
            name='questionnaire_relevant_work_links',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='coverletter',
            name='questionnaire_self_introduction',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='coverletter',
            name='text',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='URL',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='acceptance_chance_feeling',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='application_sent_done',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='comments',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='contact_person',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='cover_letter_done',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='date_apply',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='date_posted',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='documents_prep_time_feeling',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('normal', 'Normal'), ('low', 'Low')], default='medium', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='eligible_pre_check_good_idea',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='eligible_pre_check_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='extracted_key_words',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='interview_call',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='interview_call_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='position',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='priority',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='proofreading_done',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='resume_done',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
