# Generated by Django 4.2.4 on 2023-10-03 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('JAB_Main', '0018_alter_source_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='comments',
            new_name='reference_notes',
        ),
        migrations.AddField(
            model_name='coverletter',
            name='reference_type',
            field=models.CharField(blank=True, choices=[('reply_pos', 'Reply Pos'), ('reply_neg', 'No Reply'), ('neutral', 'Neutral')], default='neutral', max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='ReferenceProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_title', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('reference_about', models.TextField(blank=True, default='', null=True)),
                ('reference_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('reference_company', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('reference_description', models.TextField(blank=True, default='', max_length=255, null=True)),
                ('reference_problem_statement', models.TextField(blank=True, default='', max_length=255, null=True)),
                ('reference_to_whom_solve', models.TextField(blank=True, default='', max_length=255, null=True)),
                ('reference_bottleneck_solve', models.TextField(blank=True, default='', max_length=255, null=True)),
                ('reference_time_taken', models.TextField(blank=True, default='', max_length=255, null=True)),
                ('reference_solution', models.TextField(blank=True, default='', max_length=255, null=True)),
                ('reference_results', models.TextField(blank=True, default='', max_length=255, null=True)),
                ('reference_testimonials', models.TextField(blank=True, default='', max_length=255, null=True)),
                ('reference_visuals', models.TextField(blank=True, default='', max_length=255, null=True)),
                ('reference_skills', models.TextField(blank=True, default='', max_length=255, null=True)),
                ('reference_links', models.TextField(blank=True, default='', max_length=255, null=True)),
                ('reference_to_portfolio', models.BooleanField(blank=True, default=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reference_project_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
