# Generated by Django 4.2.4 on 2023-10-03 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('JAB_Main', '0020_alter_coverletter_reference_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referenceproject',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reference_project_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
