# Generated by Django 4.2.4 on 2023-10-20 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('JAB_Main', '0023_member_openai_enable'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireCustom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionnaire', models.CharField(blank=True, max_length=255, null=True)),
                ('questionnaire_ans', models.CharField(blank=True, max_length=255, null=True)),
                ('job', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_custom_job', to='JAB_Main.job')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_custom_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
