# Generated by Django 4.2.4 on 2023-10-20 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JAB_Main', '0024_questionnairecustom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnairecustom',
            name='questionnaire',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='questionnairecustom',
            name='questionnaire_ans',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
