# Generated by Django 4.2.4 on 2023-10-23 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JAB_Main', '0029_questionnaire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnairecustom',
            name='questionnaire',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_custom_questionnaire', to='JAB_Main.questionnaire'),
        ),
    ]
