# Generated by Django 4.2.4 on 2023-10-23 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JAB_Main', '0030_alter_questionnairecustom_questionnaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnairecustom',
            name='questionnaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_custom_questionnaire', to='JAB_Main.questionnaire'),
        ),
    ]
